name: Resume CI Build
 
on:

  push:

    branches: [ "main" ]

  pull_request:

    branches: [ "main" ]
 
jobs:

  build:

    runs-on: ubuntu-latest
 
    steps:

      - name: Checkout code

        uses: actions/checkout@v4
 
      - name: Build the Docker image with run number tag

        run: docker build . --file Dockerfile --tag myresume:${{ github.run_number }}
 
      - name: Build the Docker image with latest tag

        run: docker build . --file Dockerfile --tag myresume:latest
 
      - name: Log in to Docker Hub

        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
 
      - name: Tag image with run number for Docker Hub

        run: docker tag myresume:${{ github.run_number }} ${{ secrets.DOCKER_USERNAME }}/myresume:${{ github.run_number }}
 
      - name: Tag image with latest for Docker Hub

        run: docker tag myresume:latest ${{ secrets.DOCKER_USERNAME }}/myresume:latest
 
      - name: Push tagged images to Docker Hub

        run: |

          docker push ${{ secrets.DOCKER_USERNAME }}/myresume:${{ github.run_number }}

          docker push ${{ secrets.DOCKER_USERNAME }}/myresume:latest

 